@hostname = localhost
@port = 7157
@host = {{hostname}}:{{port}}/api
@contentType = application/json

GET https://localhost:7044/api/Auteurs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNeVN1YmplY3QiLCJqdGkiOiI3ZmM4Y2RjYi0wMmIzLTQyOGEtOTZjNS1lYzE0ZDg0MjE1N2EiLCJpYXQiOiIxMS8wNC8yMDIyIDEzOjIzOjI0IiwiSWQiOiIzIiwiTG9naW4iOiJzdHJpbmciLCJleHAiOjE2NDk2ODM0NjQsImlzcyI6Ik15SXNzdWVyIiwiYXVkIjoiTXlBdWRpZW5jZSJ9.08yVfjSSarECkRdsKQBtsYGs8OABwF73fDIKhQ4Wzw4


